export const menuItems = [
  { id: 1, name: 'Al Puchino', price: 7.0, category: 'specialty' },
  { id: 2, name: 'Zoomer', price: 7.0, category: 'specialty' },
  { id: 3, name: 'Lavender Matcha Latte', price: 7.5, category: 'specialty' },
  { id: 4, name: 'Organic Matcha Latte', price: 7.0, category: 'specialty' },
  { id: 5, name: 'Nines', price: 7.0, category: 'specialty' },
  { id: 6, name: 'Black Sesame Latte', price: 7.0, category: 'specialty' },
  { id: 7, name: 'Lavender Latte', price: 7.0, category: 'specialty' },
  { id: 8, name: 'Okie Dokie Latte', price: 7.0, category: 'specialty' },
  { id: 9, name: 'Chagaccino Latte', price: 7.5, category: 'specialty' },
  { id: 10, name: 'Spiced Beet Latte', price: 6.5, category: 'other' },
  { id: 11, name: 'Hot Chocolate', price: 5.5, category: 'other' },
  { id: 12, name: 'Organic Tea', price: 4.5, category: 'other' },
  { id: 13, name: 'Organic Herbal Tea', price: 4.5, category: 'other' },
  { id: 14, name: 'Chai Latte', price: 6.5, category: 'other' },
  { id: 15, name: 'Dirty Chai Latte', price: 7.0, category: 'other' },
  { id: 16, name: 'Organic Matcha Latte', price: 7.0, category: 'other' },
  { id: 17, name: 'Lavender Matcha Latte', price: 7.5, category: 'other' },
  { id: 18, name: 'Bagel', price: 4.5, category: 'food' },
  { id: 19, name: 'Vegan Bagel', price: 4.5, category: 'food' },
  { id: 20, name: 'Cali Bagel', price: 8.0, category: 'food' },
  { id: 21, name: 'Hot Smoked Fish Bagel', price: 14.0, category: 'food' },
  { id: 22, name: 'Bacon, Egg & Crossaint', price: 9.5, category: 'food' },
  { id: 23, name: 'Grilled Cheese on Sourdough', price: 11.0, category: 'food' },
  { id: 24, name: 'Avocado Toast', price: 14.0, category: 'food' },
  { id: 25, name: 'Peanut Butter Toast', price: 11.5, category: 'food' },
  { id: 26, name: 'Nutella Toast', price: 11.5, category: 'food' },
  { id: 27, name: 'French Toast', price: 14.5, category: 'food' },
];

